[package]
name = "day5_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0" # An implementation of regular expressions for Rust. This implementation uses finite automata …
